rolling:
  window: 30
  model: dc_state_space
  window_giornate: 8
  step: 1
folds: 3
policy:
  mode: "conformal-kelly"
  alpha: 0.1
  mondrian_keys: ["Div", "OverroundBin"]
  window: 10
  edge_thr: 0.02
  kelly_cap: 0.15
  max_width: 0.35
  variance_penalty: 0.0
