rolling:
  window: 30
  model: dc_state_space
  window_giornate: 8
  step: 1
folds: 3
policy:
  mode: "conformal-kelly"
  alpha: 0.1
  mondrian_keys: ["Div", "OverroundBin"]
  window: 10
  edge_thr: 0.02
  kelly_cap: 0.15
  max_width: 0.35
  variance_penalty: 0.0
bandit:
  algo: "linucb"
  alpha: 1.0
  epsilon: 0.02
  prior_lambda: 1.0
  decay: 0.995
  gamma_crra: 2.0
  action_space:
    edge_thr: [0.01, 0.02, 0.03, 0.05, 0.08]
    kelly_cap: [0.10, 0.15, 0.20, 0.25]
  constraints:
    max_width: 0.35
    min_liquidity_books: 3

diagnostics:
  enable: true
  reliability_bins: 15
  pit_enable: true
  regime:
    algo: "kmeans"
    min_cluster_size: 50
    k_grid: [3, 4, 5]
  leakage:
    strict: true
