dc_state_space:
  max_goals: 6
  init_rho: -0.05
  rho_bounds: [-0.2, 0.2]
  max_em_iter: 8
  em_tol: 1e-4
  q:
    atk: 0.02
    def: 0.02
    home_adv: 0.005
    rho: 0.002
  center_states: true
  min_matches_team: 6
model_a:
  learning_rate: 0.1
model_b:
  depth: 3

bivar_poisson:
  max_goals: 6
  max_iter: 200
  tol: 1e-6
  reg_lambda12: 1e-3

meta_learner:
  lib: lightgbm
  params:
    num_leaves: 31
    learning_rate: 0.05
    n_estimators: 500
    min_data_in_leaf: 50
  calibrate: true

conformal:
  alpha: 0.1
  mondrian_keys: []
  min_group_size: 100
  width_cap: 0.6
