name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install package (with dev extras)
        run: |
          pip install -e .[dev] || true
          # fallback nel caso gli extras non fossero risolti (vecchie pip):
          pip install -e .
          pip install pytest pytest-cov
      - name: Validate key spec
        run: python -m engine.ingest.keys --check
      - name: Run tests
        run: python -m pytest -q
