name: CI

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Smoke test CLI
        run: python -m engine.pipeline --rebuild-canonical --div I1 --seasons all
      - name: Smoke test market
        run: python -m engine.pipeline --build-market --div I1 --train-ratio 0.8 --calibrate
      - name: Quick backtest (optional)
        run: python -m engine.pipeline --ev-min 0.02 --stake-mode fixed --stake-fraction 0.01 --div I1
        continue-on-error: true
